### PR TITLE
Improve npm scripts and fix npm test

### PR DESCRIPTION
**Pull request by Mogztter**
## What I did

- Add `.vscode-test/` in `.gitignore` (now that tests are running!)
- Introduce a new npm task `dev`:
   - Build `preview-src` using Webpack in development mode
   - Compile `src` (using `tsc`) using `-watch` mode
- Remove npm `prune-branches` and `clean` tasks
- Fix npm `test` task 
- Call `compile` before running the `test` task
- Update `package` task:
   - Build `preview-src` using Webpack in production mode
   - Compile `src` (using `tsc`)
   - Call `vsce package`
- Introduce a new npm task to "watch"
- Rename `src-preview` to `preview-src` (less confusing and matches https://github.com/microsoft/vscode/tree/main/extensions/markdown-language-features structure)
- Rename `test` to `test-workspace` (less confusing and matches https://github.com/microsoft/vscode/tree/main/extensions/markdown-language-features structure)
- Add mocha as a development dependency (tests rely on it)
- Update `src/test/suite/index.ts`:
  - Replace `mocha.useColors(true);` (it was removed from `mocha`)
- Remove `test/extension.test.ts` and `test/index.ts` as they were unused
- Update `.vscode/launch.json` and `.vscode/tasks.json` according to all these changes
- Only include the `src` directory in `tsconfig.json` (previously `tsc` was building everything ending with *.ts)

With all these changes, I'm able to run tests locally with `npm t`.
I didn't fix all the tests in failure but now we have the proper workflow to add and run tests.

I'm also able to debug both the extension and the tests.

### CODE REVIEW

**Comment by danyill** [comment]
> I'm also able to debug both the extension and the tests.

I couldn't debug/run the extension from this PR whether or not I merged #451. I think it hangs because of the `watch` task included in the `dev` task.

**Comment by Mogztter** [comment]
That's strange... I will try again and describe the steps I took.

For reference, this configuration is used in: https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-sample

**Comment by Mogztter** [comment]
Maybe I need to define the `npm run watch` command in the `tasks.json`: https://github.com/microsoft/vscode-extension-samples/blob/main/helloworld-sample/.vscode/tasks.json

**Comment by danyill** [comment]
> Maybe I need to define the `npm run watch` command in the `tasks.json`: https://github.com/microsoft/vscode-extension-samples/blob/main/helloworld-sample/.vscode/tasks.json

I think this is correct and have had a go myself. So far, I haven't managed to fix it but I think the following links may assist:

https://github.com/microsoft/vscode/issues/84685#issuecomment-553802790
https://github.com/microsoft/vscode/issues/6209

**Comment by danyill** [comment]
Something like this in tasks.json seems about right but please check (I don't want to commit on your branch)...

```js
// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "dev",
			"problemMatcher": [
        {
          "base": "$tsc-watch", // <-- extends the TypeScript watcher
          "background": {
            "activeOnStart": true,
            "beginsPattern": "Starting compilation in watch mode...",
            "endsPattern": "Watching for file changes"
          }
        }
      ],
			"isBackground": true,
			"presentation": {
				"reveal": "never"
			},
			"group": {
				"kind": "build",
				"isDefault": true
			}
		},
    {
      "label": "build",
      "type": "shell",
      "command": "npm run dev"
    }    
	]
}
```

I haven't quite understood the regex for `beginsPattern` and `endsPattern` but it does seem to work...

**Comment by Mogztter** [comment]
@danyill Since `watch` is a new task, we might want to leave it for now and focus on fixing existing issues.
So I would suggest that we remove `npm run watch`.
We can reintroduce this task once we fully understand how to make it work.

As a result the `dev` task will build `preview-src` using Webpack (`webpack --config webpack.config.preview.js --mode development`) and then call the `compile` task.

What do you think?

> I haven't quite understood the regex for beginsPattern and endsPattern but it does seem to work...

Me neither...

**Comment by danyill** [comment]
> What do you think?

Sure, sounds fine to me.

**Comment by Mogztter** [comment]
@danyill `watch` task removed and branch rebased on master

**Comment by danyill** [comment]
LGTM, thank you for this and the discussions.

**Review by danyill — APPROVED** [review]

**Pull request merged**
