### PR TITLE
Add kroki support

### LINKED ISSUE #215: Replace the existing plantuml support by kroki
kroki (a wrappper for many text to diagram languages, including plantuml) is already available as a plugin for asciidoctor.js :

https://kroki.io/
https://github.com/Mogztter/asciidoctor-kroki

It would be nice to be able to use it from the vscode preview.

### PR DESCRIPTION
**Pull request by pomdtr**
Closes #215 

with asciidoc.use_kroki setting set at false by default.

### CODE REVIEW

**Comment by joaompinto** [comment]
@pomdtr thanks for the conitribution

**Comment by mirogta** [comment]
@pomdtr does it only work with `"asciidoc.use_asciidoctor_js": false` ? I have a simple `adoc` page but when I preview it in VSCode it does not show the diagram. Did I miss something?

```
= Diagram Test

[plantuml,alice-bob,svg,role=sequence]
....
alice -> bob
bob -> alice
....
```

Also is it possible to configure my own kroki URL, so that I don't send potentially sensitive data to the public kroki server?

I'm running my local kroki server on http://localhost:8080 and have tried to add this to the adoc page `:kroki-server-url: http://localhost:8080` to no avail.

**Comment by anb0s** [comment]
May be security setting is not set:
image

mentioned here:
https://github.com/Mogztter/asciidoctor-kroki/issues/19#issuecomment-601575460

see also my investigations
https://github.com/asciidoctor/asciidoctor-vscode/issues/272

**Comment by mirogta** [comment]
Thanks - very useful! It was the security setting. I've completely missed it (or ignored it).

**Pull request merged**
