### PR TITLE
Prevent code execution doesn't work

### PR DESCRIPTION
**Pull request by YoshihideShirai**
Hi, @Mogztter .

I found a bug in #569 implement.
I create fix MR.
Can you check it?

### CODE REVIEW

**Comment by Mogztter** [comment]
I've updated the logic a bit so I don't know if this is an actual bug or the expected behavior. Could you please describe what you did, what was your expectation and what was the actual behavior?

Once you gave your trust the extension won't ask again *unless* you disable (and enable again) extensions registration from the settings.
It's also possible to use the command "Manage Asciidoctor.js Extensions Trust Mode" to revoke your trust (denied).

**Comment by YoshihideShirai** [comment]
Sorry for my poor explanation.

Trust mode is always allow after users select trust mode.
So, it is allow despite of selecting deny.
I think there is some confusion in the definition of the return value of conformAscidoctorExtensionsTrustMode().

**Comment by Mogztter** [comment]
Oh I see, it makes sense now.
I think you are right, let me test again.

**Comment by Mogztter** [comment]
You are indeed correct, nice catch!

**Pull request merged**
