### PR TITLE
Use ripgrep instead of vscode findFiles

### PR DESCRIPTION
**Pull request by ggrossetie**
Based on https://github.com/asciidoctor/asciidoctor-vscode/pull/909

- Remove the cache (for now)
- Ensure compatibility with VS code web

### CODE REVIEW

**Comment by ggrossetie** [comment]
@alaindresse Could you please give it a try? I removed the cache because we don't have an invalidation mechanism in case a file is removed

**Comment by ggrossetie** [comment]
On Windows it does not work:

```
Error: spawn d:\a\asciidoctor-vscode\asciidoctor-vscode\node_modules\@vscode\ripgrep\bin\rg.exe ENOENT
```

**Comment by ggrossetie** [comment]
Might be a drive letter issue since `rg.exe` is correctly downloaded:

```
D:\a\asciidoctor-vscode\asciidoctor-vscode\node_modules\@vscode\ripgrep\bin
```


```
Error: spawn d:\a\asciidoctor-vscode\asciidoctor-vscode\node_modules\@vscode\ripgrep\bin\rg.exe ENOENT
```

Or a backslash/frontslash issue.

**Comment by alaindresse** [comment]
> @alaindresse Could you please give it a try? I removed the cache because we don't have an invalidation mechanism in case a file is removed

Just gave it a try. Seems to work fine. Thank you so much !

**Pull request merged**
