### PR TITLE
updated asciidoc-kroki to v0.11.0

### PR DESCRIPTION
**Pull request by mariotoffia**
Hi and many thanks for a *great* extension!!

This enables support for excalidraw (https://github.com/excalidraw/excalidraw) by upgrading asciidoc-kroki to v0.11.0 by @Mogztter (https://github.com/Mogztter/asciidoctor-kroki).

I hope it will make to a release so my team may use this great extension without a custom install!

Cheers,
 Mario :)

### CODE REVIEW

**Comment by danyill** [comment]
LGTM, thanks for this contribution. I'll merge this.
@joaompinto could we cut a release to make these features available soon?

**Comment by joaompinto** [comment]
@danyill I will release this weekend.

**Comment by mariotoffia** [comment]
> @danyill I will release this weekend.

Thanks a lot!

Cheers,
 Mario :)

**Comment by joaompinto** [comment]
Hi, I was not able to render an excalidraw file using:
```
[excalidraw]
....
include::abc.excalidraw[]
....
```
Can you provide an asciidoc example so I can test ?

**Comment by danyill** [comment]
> Hi, I was not able to render an excalidraw file using:
> 
> ```
> [excalidraw]
> ....
> include::abc.excalidraw[]
> ....
> ```
> 
> Can you provide an asciidoc example so I can test ?

I took the example from https://kroki.io which worked both as an include and as a separate file. Something like https://gist.github.com/danyill/352e5e8ae20d5997a655aa3afdd71cf4

**Comment by joaompinto** [comment]
On my test it does not seem to be handling [excalidraw] at all:
excalidraw_issue

**Comment by danyill** [comment]
Did you update your node modules?

**Comment by joaompinto** [comment]
@danyill @mariotoffia not sure what I was doing wrong but it worked fine when testing it today, it's available on the new release 2.8.7.

Thanks for your work and patience.

**Pull request merged**
