### PR TITLE
Removed a double word, add some colons for clarity, and puctuation.

### PR DESCRIPTION
**Pull request by thepollard**
Hi, this is my first time doing a pull request and I thought I'd start with something easy like a readme.  I used asciidoctor-vscode to make some simple changes, and I hope I've done the process right.  Thanks!

### CODE REVIEW

**Comment by Mogztter** [comment]
Hello @thepollard 
It looks good thanks for your contribution!

Just one note, the commit is attached to Ratmonkey20 (and not thepollard). Not sure on which account you want your contribution to appear but you might want to run the following command locally: `git commit --amend --author="Author Name <email@address.com>" ` using the email address attached to the thepollard account.

**Review by Mogztter — APPROVED** [review]
👍🏻

**Comment by thepollard** [comment]
Hi, and thanks for your feedback.  The Ratmonkey20 account was an old one tied to my gmail account, so when I went to authenticate I accidentally picked the Google authentication and it populated that.  I thought I had uncommitted, updated my git config with the correct details, and recommitted with the correct information.  I'll see if I can figure out how to fix it to be "thepollard"

**Comment by thepollard** [comment]
Ok, I figured it out I still had the wrong email set in my git config and set it correctly.  I can't figure out how to update this particular commit with the correct name, and I'm not worried enough at this point to bother you for your time.  Feel free to publish it as it is.  Thanks!

**Comment by Mogztter** [comment]
All good then, merging!
Thanks again 👍

**Pull request merged**
