### PR TITLE
Update webpack configuration to improve file bundling

### PR DESCRIPTION
**Pull request by danyill**
When building this package there is usually a message given:

> This extension consists of 2726 files, out of which 2071 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore

I have followed the instructions from:

https://code.visualstudio.com/api/working-with-extensions/bundling-extension

and tried to make this extension conform with them.

Noting:

* we shouldn't bundle all of `node_modules` as this isn't good for performance.
* I think the only thing we need to exclude from webpack is the Asciidoctor opal version which webpack produces errors if I include it (now excluded in `webpack.config.js`)

Before: 

```bash
19:02 $ ./build.sh package
==> Packaging extension
Executing prepublish script 'npm run vscode:prepublish'...

> asciidoctor-vscode@2.7.13 vscode:prepublish /home/mulhollandd/Documents/asciidoctor-vscode
> tsc -p ./ && npm run build-preview


> asciidoctor-vscode@2.7.13 build-preview /home/mulhollandd/Documents/asciidoctor-vscode
> webpack --mode development

Hash: 287e6d0a4c7ccad2789b
Version: webpack 4.41.6
Time: 2038ms
Built at: 03/01/2020 7:02:55 PM
   Asset      Size  Chunks             Chunk Names
index.js  88.2 KiB   index  [emitted]  index
  pre.js  27.6 KiB     pre  [emitted]  pre
Entrypoint index = index.js
Entrypoint pre = pre.js
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {index} [built]
[./preview-src/activeLineMarker.ts] 1.11 KiB {index} [built]
[./preview-src/csp.ts] 2.04 KiB {pre} [built]
[./preview-src/events.ts] 659 bytes {index} [built]
[./preview-src/index.ts] 4.5 KiB {index} [built]
[./preview-src/loading.ts] 1.25 KiB {pre} [built]
[./preview-src/messaging.ts] 682 bytes {index} [built]
[./preview-src/pre.ts] 550 bytes {pre} [built]
[./preview-src/scroll-sync.ts] 4.68 KiB {index} [built]
[./preview-src/settings.ts] 1010 bytes {index} {pre} [built]
[./preview-src/strings.ts] 696 bytes {pre} [built]
    + 1 hidden module
This extension consists of 2726 files, out of which 2071 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
 DONE  Packaged: /home/mulhollandd/Documents/asciidoctor-vscode/asciidoctor-vscode-2.7.13.vsix (2726 files, 11.64MB)
 INFO  
The latest version of vsce is 1.74.0 and you have 1.71.0.
Update it now: npm install -g vsce
```

After:

```bash
19:04 $ ./build.sh package
==> Packaging extension
Executing prepublish script 'npm run vscode:prepublish'...

> asciidoctor-vscode@2.7.13 vscode:prepublish /home/mulhollandd/Documents/asciidoctor-vscode
> tsc -p ./ && npm run build-production


> asciidoctor-vscode@2.7.13 build-production /home/mulhollandd/Documents/asciidoctor-vscode
> webpack --mode production

Hash: 39a7a2a4a956669cd413
Version: webpack 4.41.6
Time: 8273ms
Built at: 03/01/2020 7:05:09 PM
       Asset      Size  Chunks             Chunk Names
extension.js  8.49 MiB       0  [emitted]  main
Entrypoint main = extension.js
  [1] external "vscode" 42 bytes {0} [built]
 [24] ./src/slugify.ts 1.14 KiB {0} [built]
[176] ./src/extension.ts 4.2 KiB {0} [built]
[177] ./src/commandManager.ts 1010 bytes {0} [built]
[178] ./src/commands/index.ts 1.77 KiB {0} [built]
[244] ./src/features/documentLinkProvider.ts 5.09 KiB {0} [built]
[246] ./src/features/documentSymbolProvider.ts 3.4 KiB {0} [built]
[247] ./src/features/previewContentProvider.ts 9.14 KiB {0} [built]
[248] ./src/features/previewManager.ts 5.13 KiB {0} [built]
[251] ./src/features/workspaceSymbolProvider.ts 6.22 KiB {0} [built]
[252] ./src/logger.ts 2.11 KiB {0} [built]
[253] ./src/asciidocEngine.ts 2.95 KiB {0} [built]
[254] ./src/asciidocExtensions.ts 2.32 KiB {0} [built]
[255] ./src/security.ts 6.58 KiB {0} [built]
[256] ./src/features/attributeCompleter.ts 754 bytes {0} [built]
    + 242 hidden modules
 DONE  Packaged: /home/mulhollandd/Documents/asciidoctor-vscode/asciidoctor-vscode-2.7.13.vsix (58 files, 5.21MB)
 INFO  
The latest version of vsce is 1.74.0 and you have 1.71.0.
Update it now: npm install -g vsce
```

I've not used webpack previously so this could likely benefit from a careful review.

### CODE REVIEW

**Comment by danyill** [comment]
Hmmm, not quite ready, still receiving an error when starting the extension in debug:

```bash
Activating extension 'joaompinto.asciidoctor-vscode' failed: Cannot find module '/home/mulhollandd/Documents/asciidoctor-vscode/dist/extension'
Require stack:
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js.
```

**Comment by danyill** [comment]
And if Asciidoctor is bundled, the stylesheet gets lost:

>ENOENT: ENOENT: no such file or directory, open '/css/asciidoctor.css'

**Comment by danyill** [comment]
@joaompinto I've had a go at making some improvements to the structure of the repository and some of the configuration files:

* Rename `preview-src` to `src-preview`
* Provide webpack configurations for both the app and the preview (removes warning during building regarding many many files)
* Disable other extensions when launching this from the source folder (avoid contamination)
* Build extension into the `dist` folder, in common with the vs code instructions
* Update `tasks.json` to `2.0.0` format
* Add items to `.vscodeignore` as per vs code instructions and to remove extraneous ts config and ts files
* Update `package.json` tasks for webpack, specifically the `vscode:prepublish` task and also create webpack tasks.
* I was uncomfortable with `index.js` and `pre.js` being built into the `media` folder so I've made some changes so they are build into the `dist` folder along with other compiled/packed assets

Could you please review/test. It is quite possible this breaks something which I didn't full understand...

**Comment by joaompinto** [comment]
I get an error when attempting to debug the extension:
Activating extension 'joaompinto.asciidoctor-vscode' failed: Cannot find module '/home/joaompinto/Projects/asciidoctor-vscode/dist/extension.js'
Require stack:
- /usr/lib/code/out/vs/loader.js
- /usr/lib/code/out/bootstrap-amd.js
- /usr/lib/code/out/bootstrap-fork.js.

**Comment by danyill** [comment]
I've rebased and tidied this up - the month of not looking at it may not have improved my understanding of things.

Debugging the extension and packaging it are both done in the `dist` folder now. I couldn't figure out how to change the entrypoint for the compiled assets with webpack from the debugging workflow so that's how it is.

I've done a handful of tests but this is a fairly substantial change so it would be good to see if we can find something I've broken. @joaompinto could you please take another look?

**Comment by joaompinto** [comment]
I will look at it, sorry if I can't really give a much help on this, javascript/typescript is not really my area of expertise/interest. Thanks for your hard work.

**Comment by danyill** [comment]
I've made a few more changes.

1. Rebased to master.
2. We've not been committing `package-lock.json` but in general this will mean (particular for the CI that @larshp set up) that we are not getting reproducible dependencies across different machines.
3. I've also modified Github Actions to install using `npm ci` instead of `npm i` in accordance with the recommendation [here](https://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable).
4. Finally I've still had some problems with ts and webpack configurations but I've rearranged the paths and I'm hoping I'm finally there (I'll keep testing locally).

This PR is becoming a terrible monolith. I'm sorry :crying_cat_face:

**Pull request merged**
